
name: Build Image and Deploy to cluster

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to repository
      run: docker login ${{secrets.DOCKER_ENDPOINT}} -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: docker pull ${{secrets.DOCKER_ENDPOINT}}/zero-tools/mikibot:latest && docker build --pull -f Mikibot.Analyze/Dockerfile . -t ${{secrets.DOCKER_ENDPOINT}}/zero-tools/mikibot:latest

    - name: Push image
      run: docker push ${{secrets.DOCKER_ENDPOINT}}/zero-tools/mikibot:latest

  deploy:
    needs: [build]
    runs-on: self-hosted
    
    steps:
    - uses: Azure/setup-kubectl@v3
      with:
        version: latest
        
    - name: Rollout k8s deployment
      run: kubectl rollout restart -n mirai deployment/mikibot
        
